### ISSUE TITLE
Question: Building a PWA/Progressive Web App?

### ISSUE THREAD

**Issue by cheako** [dunnock/wasi-worker#5]
https://www.smashingmagazine.com/2016/08/a-beginners-guide-to-progressive-web-apps/#sw-js
```caches``` is a weird thing, it's name collides with unrelated things so it's hard to get at it's documentation.    From what I gather it's like ```document```, another colliding name so I'm unable to reference what I'm trying to talk about.

Unrelated question:
I moved things around in my project, I couldn't reconcile using the same Cargo.toml for the index and worker wasm.
I wonder about this: https://gitlab.com/cheako/websuite-rs/-/blob/ad496931abfd91071117bd77af8ffc13a0a49640/notes/index/src/lib.rs#L47 this is supposed to referance a property of this JsValue, not the value itself.

**Comment by dunnock** [comment]
That first article describes on how to build custom caching for requests, IMHO using JavaScript worker for that purpose is easier. This page describes global scope for worker https://developer.mozilla.org/ru/docs/Web/API/WorkerGlobalScope

swc.register will produce ServiceWorkerRegistration in the future: https://docs.rs/web-sys/0.3.27/web_sys/struct.ServiceWorkerRegistration.html, so that should be &r.scope() I guess?

**Comment by cheako** [comment]
I'm trying to test every aspect of Rust I can, to show what the current capabilities are.  I'm not new to interfaces that need flushing out and Rust has been pleasant to work with in that regard.

In the 2ks I inherited a project that was written in 7 different languages and this causes a problem when trying to hire someone to maintain the project.  Since then I found that everything can be done in Perl, I particularly liked the CGI module where Perl syntax replaces HTML: ```print p((h2("Thing"), "the description", br(), "next line"));```
Now I think it may be time to write everything in Rust.
